export const actions = {
  /* Auth */
  LOGIN_ADULT_ASYNC: 'LOGIN_ADULT_ASYNC',
  LOGIN_CHILD_ASYNC: 'LOGIN_CHILD_ASYNC',
  LOGIN_ADULT: 'LOGIN_ADULT',
  LOGIN_CHILD: 'LOGIN_CHILD',
  SIGNUP_ADULT_ASYNC: 'SIGNUP_ADULT_ASYNC',
  SIGNUP_ADULT: 'SIGNUP_ADULT',
  SIGNUP_CHILD_ASYNC: 'SIGNUP_CHILD_ASYNC',
  SIGNUP_CHILD: 'SIGNUP_CHILD',
  SIGNUP_ASYNC: 'LOGIN_ASYNC',
  SIGNUP: 'SIGNUP',
  SEND_VERIFICATION_CODE_ASYNC: 'SEND_VERIFICATION_CODE_ASYNC',
  SEND_VERIFICATION_CODE: 'SEND_VERIFICATION_CODE',
  RESET_PASSWORD_ASYNC: 'RESET_PASSWORD_ASYNC',
  RESET_PASSWORD: 'RESET_PASSWORD',
  FORGET_PASSWORD_ASYNC: 'FORGET_PASSWORD_ASYNC',
  FORGET_PASSWORD: 'FORGET_PASSWORD',
  FETCH_SECURITY_QUESTION_ASYNC: 'FETCH_SECURITY_QUESTION_ASYNC',
  FETCH_SECURITY_QUESTION: 'FETCH_SECURITY_QUESTION',
  SUBMIT_SECURITY_QUESTION_ASYNC: 'SUBMIT_SECURITY_QUESTION_ASYNC',
  SUBMIT_SECURITY_QUESTION: 'SUBMIT_SECURITY_QUESTION',

  LOGOOUT: 'LOGOOUT',
  /* User */
  CHANGE_PROFILE_ASYNC: 'CHANGE_PROFILE_ASYNC',
  CHANGE_PROFILE: 'CHANGE_PROFILE',
  /* Documents */
  FETCH_DOCUMENTS_ASYNC: 'FETCH_DOCUMENTS_ASYNC',
  FETCH_DOCUMENTS: 'FETCH_DOCUMENTS',
  FETCH_DOCUMENT_ASYNC: 'FETCH_DOCUMENT_ASYNC',
  FETCH_DOCUMENT: 'FETCH_DOCUMENT',
  SIGN_DOCUMENT_ASYNC: 'SIGN_DOCUMENT_ASYNC',
  SIGN_DOCUMENT: 'SIGN_DOCUMENT',
  FINISH_DOCUMENT_VIDEO_ASYNC: 'FINISH_DOCUMENT_VIDEO_ASYNC',
  FINISH_DOCUMENT_VIDEO: 'FINISH_DOCUMENT_VIDEO',
  SUBMIT_DOCUMENT_QUESTIONS_ASYNC: 'SUBMIT_DOCUMENT_QUESTIONS_ASYNC',
  SUBMIT_DOCUMENT_QUESTIONS: 'SUBMIT_DOCUMENT_QUESTIONS',
  SEARCH_DOCUMENTS_ASYNC: 'SEARCH_DOCUMENTS_ASYNC',
  SEARCH_DOCUMENTS: 'SEARCH_DOCUMENTS',

  /* Children */
  FETCH_CHILDREN_AYSNC: 'FETCH_CHILDREN_ASYNC',
  FETCH_CHILDREN: 'FETCH_CHILDREN',
};

export const OTP_METHODS = {
  SMS: 'SMS',
  EMAIL: 'EMAIL',
};
