export const types = {
  LOGIN_PARENT_ASYNC: 'LOGIN_PARENT_ASYNC',
  LOGIN_CHILD_ASYNC: 'LOGIN_CHILD_ASYNC',
  LOGIN_PARENT: 'LOGIN_PARENT',
  LOGIN_CHILD: 'LOGIN_CHILD',
  FETCH_DOCUMENTS_ASYNC: 'FETCH_DOCUMENTS_ASYNC',
  FETCH_DOCUMENTS: 'FETCH_DOCUMENTS',
  FETCH_CHILDREN_AYSNC: 'FETCH_CHILDREN_ASYNC',
  FETCH_CHILDREN: 'FETCH_CHILDREN',
  SIGNUP_ASYNC: 'LOGIN_ASYNC',
  SIGNUP: 'SIGNUP',
  LOGOOUT: 'LOGOOUT',
};
