export const types = {
  /* Auth */
  LOGIN_ADULT_ASYNC: 'LOGIN_ADULT_ASYNC',
  LOGIN_CHILD_ASYNC: 'LOGIN_CHILD_ASYNC',
  LOGIN_ADULT: 'LOGIN_ADULT',
  LOGIN_CHILD: 'LOGIN_CHILD',
  SIGNUP_ADULT_ASYNC: 'SIGNUP_ADULT_ASYNC',
  SIGNUP_ADULT: 'SIGNUP_ADULT',
  SIGNUP_CHILD_ASYNC: 'SIGNUP_CHILD_ASYNC',
  SIGNUP_CHILD: 'SIGNUP_CHILD',
  SIGNUP_ASYNC: 'LOGIN_ASYNC',
  SIGNUP: 'SIGNUP',
  SEND_VERIFICATION_CODE_ASYNC: 'SEND_VERIFICATION_CODE_ASYNC',
  SEND_VERIFICATION_CODE: 'SEND_VERIFICATION_CODE',
  LOGOOUT: 'LOGOOUT',
  /* Documents */
  FETCH_DOCUMENTS_ASYNC: 'FETCH_DOCUMENTS_ASYNC',
  FETCH_DOCUMENTS: 'FETCH_DOCUMENTS',
  /* Children */
  FETCH_CHILDREN_AYSNC: 'FETCH_CHILDREN_ASYNC',
  FETCH_CHILDREN: 'FETCH_CHILDREN',
};
